### ISSUE TITLE
Allow cluster across helm deployment by chart name

### ISSUE THREAD

**Issue by lucascicco** [pelotech/drone-helm3#113]
**The problem I'm trying to solve:**
I've multiples applications that are deployed based on the same helm chart across the whole cluster (multi namespace), in addiction, this plugin is fully complete to handle with multiples helm actions (upgrade, uninstall), however only works for a single helm release by namespace, and in my case, I want to use the same configuration at the same pipeline to take an action for each release in the cluster releated to that desired helm chart (filtering across the cluster by the helm chart name).

E.g:
![image](https://user-images.githubusercontent.com/40899243/188206821-67c53d60-9061-4ed5-a6b7-a81852f62b87.png)

**How I imagine it working:**
Passing a new parameter, such as "**chart_name_selector**" in the **drone.yml** file to make this multi namespace release work.

```yaml
- name: push_master_deploy_production
  image: pelotech/drone-helm3
  settings:
    mode: upgrade
    chart_name_selector: floki
    chart: ./kube
    values: image.tag=${DRONE_COMMIT_SHA}
    values_files: ./kube/production.yaml
    skip_tls_verify: true
    kube_api_server:
      from_secret: api_server
    kube_token:
      from_secret: kubernetes_token
  when:
    event: [push]
    branch: [master]
    status: [success]
```
