### ISSUE TITLE
Implement the prefix setting

### ISSUE THREAD

**Issue by ErinCall** [pelotech/drone-helm3#19]
drone-helm allows the drone chart to set a prefix to be used when looking up environment variables. For example, given this stanza:

```yaml 
environment:
  prefix: FOO
  foo_token: fjejkdkfjfj
```

It will look for the token setting in `FOO_TOKEN` rather than `TOKEN`. 

We should retain support for that feature.
