### ISSUE TITLE
Remove the `prefix` setting

### ISSUE THREAD

**Issue by ErinCall** [pelotech/drone-helm3#48]
The `prefix` setting in internal/helm/config.go exists because it existed in drone-helm. As I've learned more about drone usage, it's become clear it's not needed. It was meant to support a `.drone.yml` stanza like this:

```yaml
pipeline:
  steps:
    - name: deploy_staging
      image: pelotech/drone-helm3
      prefix: stage
      secrets: [stage_kubernetes_token]
```

That `secrets` syntax is deprecated in recent versions of drone, and might not work at all. A modern stanza would look like this:

```yaml
pipeline:
  steps:
    - name: deploy_staging
      image: pelotech/drone-helm3
      kubernetes_token:
        from_secret: stage_kubernetes_token
```

* Remove the setting and associated code from config.go
* Remove any mention of the setting (including the "using the `prefix` setting" section) from parameter_reference.md
* In the "upgrading from drone-helm" section of the README, add a note that the old syntax needs to be replaced
