### ISSUE TITLE
force_upgrade is being ignored

### ISSUE THREAD

**Issue by iron-sam** [pelotech/drone-helm3#92]
**My drone-helm3 and drone versions:**
`drone:1.7.0`
`pelotech/drone-helm3:latest`

**What I tried to do:**
We have an automatic nightly deployment that refreshes actual deployment with the same image tag, so we use `force_upgrade` parameter to tell Helm to recreate pods even if the same tag is present

**What happened:**
When the nightly deployment triggers, everything works fine, but pods aren't restarted:

```
$ helm history website 
REVISION        UPDATED                         STATUS          CHART           APP VERSION     DESCRIPTION     
160             Thu May 21 08:07:13 2020        superseded      trevor-2.3.0    1.0             Upgrade complete # <- Latest CI/CD automatic deploy
161             Fri May 22 00:18:02 2020        deployed        trevor-2.3.0    1.0             Upgrade complete # <- Nightly deploy

$ date
vie 22 may 2020 10:30:42 CES

$ kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
website-78f6d94c79-trt58   2/2     Running   0          24h
website-78f6d94c79-vjbk5   2/2     Running   0          24h
```

As you can see, pods should have ~12h age if nightly deployment refreshed pods, but instead, it has ~24h, since latest CI/CD deployment.

As far as I know, `force_upgrade` send `helm` the `--force` flag, which `force resource updates through a replacement strategy`, am I wrong?

**More info:**
The `.drone.yml` step:

```
  - name: helm_deploy
    image: pelotech/drone-helm3
    settings:
      mode: upgrade
      chart: my/chart
      force_upgrade: true
      add_repos: my_repo=http://charts.example.com
      namespace: ${DRONE_REPO_NAME}
      release: ${DRONE_REPO_NAME}
      kube_service_account: system:serviceaccount:helm:helm
      values: istio.hosts[0]=www.example.com,fullnameOverride=${DRONE_REPO_NAME},image.repository=${DRONE_REPO_NAME}
      values_files:
        - ./cicd/templates/values.yaml
      wait_for_upgrade: true
      kube_api_server:
        from_secret: production_api_server
      kube_token:
        from_secret: production_kubernetes_token
      kube_certificate:
        from_secret: production_k8s_ca
```
Also, `values.yaml` have a `pullPolicy: Always` configuration to force Kubernetes to always download the image even if same tag is provided.

This is the output of `helm_deploy` step on Drone web UI:

```
"chart" has been added to your repositories
Release "website" has been upgraded. Happy Helming!
NAME: website
LAST DEPLOYED: Fri May 22 07:32:14 2020
NAMESPACE: website
STATUS: deployed
REVISION: 162
TEST SUITE: None
NOTES:
Get project URL by running these commands:

    https://www.example.com
```
Thank you very much!

**Comment by josmo** [comment]
@iron-sam when I get a chance I'll take a look, however I believe that's a helm issue where something needs to change to re-pull. In my cases I usually add an annotation to the deployment with the build number/deploy time something like 
```
      timeout: 200s
      update_dependencies: true
      values:
        - image.tag=latest
        - "podAnnotations.deployedDate=\"${DRONE_BUILD_CREATED}\""
        - "podAnnotations.buildNumber=\"${DRONE_BUILD_NUMBER}\""
```
